# Generated by Django 3.1.7 on 2021-03-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='images/none/no_img.jpg', upload_to='images/'),
        ),
    ]
